services:
  product-demos:
    image: ridgerun/products-evals-demos:x86_ubuntu20_v0.1
    network_mode: "host"
    ipc: host
    cap_add: 
      - SYS_NICE
    devices:
      - "/dev/snd:/dev/snd"
      - "/dev/video0:/dev/video0"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $PWD:/product-demo/ridgerun-products-demos
    environment:
      - DISPLAY=$DISPLAY
    working_dir: /product-demo
    command: /bin/bash demo.sh
    entrypoint: /product-demo/demo.sh
